- name: deployapp
  hosts: web1
  become: true
  tasks: 
    

    - name: Copy your file
      copy:
        src: ./Booster_CI_CD_Project.zip
        dest: ~/
    
    - name: install zip
      apt:
        name: zip
        state: present

    - name: unzip
      unarchive:
        src: ~/Booster_CI_CD_Project.zip
        dest: ~/
        remote_src: yes

    - name: install PYTHON3
      apt:
        name: python3 
        state: present 

      
    - name: install pip3
      apt:
        update_cache: yes
        name: python3-pip 
        state: present 

    - name: install DEPENDANCIES
      pip:
        requirements: ~/Booster_CI_CD_Project/requirements.txt
        executable: pip3

    - name: make migration
      command: "python3 ~/Booster_CI_CD_Project/manage.py makemigrations"

    - name:  migrate
      command: "python3 ~/Booster_CI_CD_Project/manage.py migrate"

    - name: start the server
      command: "python3 ~/Booster_CI_CD_Project/manage.py runserver 0.0.0.0:8000"

