- name: install apache2
  hosts: aws
  become: true
  tasks: 
    - name: install apache 
      apt:
        name: apache2
        state: present
 
    - name: Copy your index file
      copy:
        src: "./index.html"
        dest: "/var/www/html/index.html"
 
    - name: apache2 listen on port 8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted